### ISSUE TITLE
Push jobs fails to install correctly

### ISSUE THREAD

**Issue by axelrtgs** [chef/opscode-pushy-client#125]
# Description

push jobs fails to install correctly. some dependencies seem to be missing so it cannot start the service and fails

# Push Jobs Client Version

2.2.0

# Platform Version

Windows Server 2008R2

# Replication Case

Method 1: use pushjobs cookbook to update the push jobs client to 2.2.0 > Result is pushjobs service fails to start

Method 2: uninstall manually old version and install version 2.2.0 from scratch > > Result is pushjobs service fails to start

Method 3: manually run installer for 2.2.0 without uninstalling old version first > Result is pushjobs service fails to start

# Stacktrace
```
[2017-04-04T14:39:12-04:00] FATAL: SystemCallError: windows_service[push-jobs-client] (push-jobs::service_windows line 6
3) had an error: SystemCallError: The service did not respond to the start or control request in a timely fashion. - Sta
rtService: The service did not respond to the start or control request in a timely fashion.


PS C:\Users\Administrator> c:\opscode\push-jobs-client\embedded\bin\ruby.exe c:\opscode\push-jobs-client\embedded\lib\ru
by\gems\2.3.0\gems\opscode-pushy-client-2.2.0\lib\pushy_client\windows_service.rb -c C:\chef/push-jobs-client.rb
Unable to load this gem. The libzmq library (or DLL) could not be found.
If this is a Windows platform, make sure libzmq.dll is on the PATH.
If the DLL was built with mingw, make sure the other two dependent DLLs,
libgcc_s_sjlj-1.dll and libstdc++6.dll, are also on the PATH.
For non-Windows platforms, make sure libzmq is located in this search path:
["C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/ffi-rzmq-core-1.0.5/lib/ffi-rzmq-core/../../ext/libzmq.d
ll", "%SystemRoot%\\system32\\WindowsPowerShell\\v1.0\\/libzmq.dll", "c:\\Program Files\\7-Zip\\/libzmq.dll", "C:\\Windo
ws\\system32/libzmq.dll", "C:\\Windows/libzmq.dll", "C:\\Windows\\System32\\Wbem/libzmq.dll", "C:\\Windows\\System32\\Wi
ndowsPowerShell\\v1.0\\/libzmq.dll", "C:\\opscode\\chef\\bin\\/libzmq.dll", "C:/opscode/push-jobs-client/embedded/lib/li
bzmq.dll", "/usr/local/lib/libzmq.dll", "/opt/local/lib/libzmq.dll", "/usr/lib64/libzmq.dll"]
C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/ffi-rzmq-core-1.0.5/lib/ffi-rzmq-core/libzmq.rb:57:in `res
cue in <module:LibZMQ>': The libzmq library (or DLL) could not be loaded (LoadError)
        from C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/ffi-rzmq-core-1.0.5/lib/ffi-rzmq-core/libzmq.
rb:10:in `<module:LibZMQ>'
        from C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/ffi-rzmq-core-1.0.5/lib/ffi-rzmq-core/libzmq.
rb:7:in `<top (required)>'
        from C:/opscode/push-jobs-client/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `re
quire'
        from C:/opscode/push-jobs-client/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `re
quire'
        from C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/ffi-rzmq-core-1.0.5/lib/ffi-rzmq-core.rb:3:in
 `<top (required)>'
        from C:/opscode/push-jobs-client/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `re
quire'
        from C:/opscode/push-jobs-client/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `re
quire'
        from C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/ffi-rzmq-2.0.4/lib/ffi-rzmq.rb:66:in `<top (r
equired)>'
        from C:/opscode/push-jobs-client/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `re
quire'
        from C:/opscode/push-jobs-client/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `re
quire'
        from c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/opscode-pushy-client-2.2.0/lib/pushy_client/p
rotocol_handler.rb:18:in `<top (required)>'
        from c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/opscode-pushy-client-2.2.0/lib/pushy_client.r
b:21:in `require_relative'
        from c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/opscode-pushy-client-2.2.0/lib/pushy_client.r
b:21:in `<top (required)>'
        from c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/opscode-pushy-client-2.2.0/lib/pushy_client/w
indows_service.rb:25:in `require_relative'
        from c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.3.0/gems/opscode-pushy-client-2.2.0/lib/pushy_client/w
indows_service.rb:25:in `<main>'
```

**Comment by btm** [comment]
Downgrading to 2.1.4 is the current workaround.

**Comment by btm** [comment]
Created internally as BUG-409.
