### ISSUE TITLE
ASCII-8BIT to UTF-8 - Encoding Error on Push Job Client

### ISSUE THREAD

**Issue by girish-harthikote** [chef/opscode-pushy-client#129]
# Description

Recently clients are upgraded to version 13.0.118, later client upgrade we are facing issue with push job.

After resource update on client (chef node) is successful, when push job client trying to communicate to chef server  
**"\xEF" from ASCII-8BIT to UTF-8** - exception is raised.

Push Job is waiting for response. Execution does not end.

# Push Jobs Client Version

opscode-pushy-client-2.1.4

**Chef Client Version**

Chef: 13.0.118

# Platform Version

Windows Server 2008 R2 64 bit

# Replication Case

Tell us what steps to take to replicate your problem. See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) for information on how to create a good replication case.

# Stacktrace

Job d2e39b6c09c2bb33d6a0077d6e05f2ce completed with exit code 0
Exception raised while waiting for job d2e39b6c09c2bb33d6a0077d6e05f2ce to complete: "\xEF" from ASCII-8BIT to UTF-8
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/json-2.0.2/lib/json/common.rb:224:in `encode'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client/protocol_handler.rb:470:in `block in send_signed_json_command'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client/protocol_handler.rb:467:in `synchronize'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client/protocol_handler.rb:467:in `send_signed_json_command'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client/protocol_handler.rb:206:in `send_command'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client.rb:168:in `send_command'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client/job_runner.rb:200:in `block in completed'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client/job_runner.rb:193:in `synchronize'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client/job_runner.rb:193:in `completed'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client/job_runner.rb:244:in `block in start_process'

**Comment by vadimkl** [comment]
I've run into this issue myself. After a bit of investigation, it seems like the issue happens due to the fact that STDOUT part of the "succeeded" command can potentially contain textual outputs from different application or files on the client node that might be stored in all kinds of different encoding.

In my case, a recipe is trying to copy the content from one file into another through the use of Chefs "file" resource. The "file" resource will then output parts of the file content as part of the chef-run logs. If the file happens to contain some special bits at the start of the file, like the BOM in case of a UTF-8 text files, these special characters end up also being part of the chef-run log.  Heres a somewhat sanitized example of what is happening on my end:

`* file[C:/some_file.config] action create\r\n`
`  - update content in file C:/some_file.config from 5feacc to dce693\r\n`
` --- C:/some_file.config\r\n`
` +++ C:/chef-some_file20181115-4664-7aryfa.config\r\n`
` [37m@@ -1,7 +1,7 @@\r\n`
` [37m \xEF\xBB\xBF<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n`
` [37m <configuration>\r\n`
` [37m   <connectionStrings>\r\n`
` [37m-    <add name=\"ConnStr\" connectionString=\"Server=localhost;Database=DB1;\" />\r\n`
` [37m+    <add name=\"ConnStr\" connectionString=\"Server=localhost;Database=DB2;\" />\r\n`
` [37m   </connectionStrings>\r\n`
` [37m   <appSettings>\r\n`

The \xEF\xBB\xBF is part of the xml file and is part of the UTF-8 BOM. The problem happens when the pushy-client code tries to convert the STDOUT content into a JSON as part of the "succeeded" command that it sends to the server. It seems that the JSON.generate isn't capable of handling this properly and a said exception is thrown. The irony is that the actual run has succeeded, but due to the issue with log serialization we get an exception, and in the end, the entire job is marked as timed out.

I would assume that since the content of the STDOUT can be completely arbitrary, it might be tricky to ensure that it will be handled properly all the time for all possible cases. But what I do think could be done, is that the "succeeded" and "failed" commands that are sent to the server should be stripped from  the STDOUT and STDERR logs. Instead, these logs should be sent in their own separate command. 

Implemented that way, the delivery of the status messages should have a smaller probability of going wrong since their content can be controlled. This would ensure that in the worst case scenario we at least get the right state of the chef run, and only the logs will be lost or mishandled if the are some issues with sending or serializing them properly.

I'm not sure if this is a Windows only problem, but whilst looking around, I saw in the push-job-client.rb file an attempt to set the encoding through an environment variable.

`LC_ALL='en_US.UTF-8'`

This seems to have no effect on Windows, so that might also be contributing to this issue, though I'm not a ruby developer, so my knowledge is quite limited on this.

@markan I assume that you look over this project. Can you comment on this?

**Comment by markan** [comment]
Ugh. Your diagnosis seems pretty reasonable; we've seen issues like this with mixing codepages and UTF8. 
Changing the output to go in a separate packet would require a protocol change I think, which isn't ideal. 

A somewhat hackish workaround would be to wrap the json encoding step in a rescue, and retry there without STDIN/STDERR output.

**Comment by zanecodes** [comment]
A cleaner solution might be to simply encode the `stdout` and `stderr` to UTF-8 _before_ passing it to `JSON.generate`, and pass [`invalid: :replace, undef: :replace, replace: '?'` to String#encode.](https://ruby-doc.org/core-2.1.3/String.html#method-i-encode)
This would mangle the output slightly, but it's strictly better than having the client fail to send the packet and causing the push job to hang indefinitely.
The best solution would probably be to make no assumptions about the contents of `stdout` and `stderr` since they could contain arbitrary bytes, and just base64 encode them before stuffing them into the JSON object and make the reader deal with interpreting it, but this is a breaking change.

**Comment by vadimkl** [comment]
Seeing that there's no clean way of solving it without introducing a breaking change, perhaps a new version of protocol needs to be created, with an option on the client side that would allow to choose which version to use. This way this issue could be addressed in a clean manner without breaking anything for the existing setups, whilst not being limited by the compatibility issue.

**Comment by danielcbright** [comment]
@markan can this get flagged as a bug? I'm seeing this issue come up now with a couple of customers who are upgrading to and past client 13.
